spring.application.name=TaskManager

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=18fe50e388700e36624cb8bd986a48ea3b6e050c5d01e2058d6b0e53f66da731

spring.security.user.name=admin
spring.security.user.password=admin